# Generated by Django 2.1.7 on 2020-03-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('color_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
